import { ResourceManager } from "@/utils/resource.manager";
import { ResourceId } from "@/generated/resourceTypes";
import { hullsData, toHullBlueprint } from "@/config/hulls.data";
import { turretsData, toTurretBlueprint } from "@/config/turrets.data";

// Resource keys (in resourceTypes.ts) for the supply preview icons. The actual images were
// downloaded from the official CDN into resources/bonuses/<X>/preview, so they're served by OUR
// resource server with our own idLows — works for any client.
export const supplyPreviewResources: Record<string, ResourceId> = {
    health: "bonuses/health/preview",
    armor: "bonuses/armor/preview",
    double_damage: "bonuses/damage/preview",
    n2o: "bonuses/nitro/preview",
    mine: "bonuses/mine/preview",
    "1000_scores": "bonuses/scores/preview",
};

export const itemBlueprints = {
    turrets: turretsData.map(toTurretBlueprint),
    hulls: hullsData.map(toHullBlueprint),
    paints: [
        {
            id: "green",
            name: "Verde",
            description: "Um tributo à tradição do tanque clássico, esta cor simples, tão amada por designers de todo o mundo, tornou-se uma tinta padrão para modelos de fábrica.",
            isInventory: false,
            index: 1100,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/green/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/green/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/green/texture"),
        },
        {
            id: "holiday",
            name: "Feriado",
            description: "Uma tinta única e «inteligente» que pode mudar sua aparência dependendo da ocasião. Em um dia normal, é simplesmente uma textura quadriculada em preto e branco. Mas quando chega um feriado, sua aparência muda drasticamente.",
            isInventory: false,
            index: 1200,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/holiday/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/holiday/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/holiday/texture"),
        },
        {
            // Pintura ANIMADA (cicla-cor): coloring type 11 / image.tara (tira 1000x1, 1000 frames, 15fps).
            id: "spectrum",
            name: "Espectro",
            description: "Esta pintura foi desenvolvida com as mais recentes tecnologias de pesquisa quântica, que permitem aplicar efeitos de probabilidade ao macromundo. A primeira ideia dos criadores foi finalmente realizar o experimento do gato de Schrödinger, mas foi barrada pelos ativistas dos direitos dos animais. Então, em vez disso, fizeram esta pintura. Se você não se importa com toda a matemática complexa e a pesquisa científica, é só uma pintura monocromática de cor verde... espera, azu... espera... vermelha. Ah, pelo amor de...! Amarela! AAA! Roxa! Chega, desisto, escreva você mesmo esta descrição.",
            isInventory: false,
            index: 1201,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/spectrum/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/spectrum/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/spectrum/texture"),
        },
        {
            id: "red",
            name: "Vermelha",
            description: "A cor vermelha - a personificação da raiva e da coragem. Também tem a aplicação prática de poder esconder qualquer vestígio de sangue inimigo.",
            isInventory: false,
            index: 2850,
            next_price: 100,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/red/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/red/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/red/texture"),
        },
        {
            id: "blue",
            name: "Azul",
            description: "Esta pintura foi adicionada à lista oficial em memória de um projeto fracassado - o desenvolvimento de um tanque anfíbio codinome «Catfish». Os designers estavam planejando dar ao <Catfish> a capacidade de se mover sob as águas de rios rasos, permitindo que ele tomar posição atrás das linhas inimigas. A cor azul seria perfeita para camuflagem.",
            isInventory: false,
            index: 2900,
            next_price: 100,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/blue/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/blue/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/blue/texture"),
        },
        {
            id: "black",
            name: "Preta",
            description: "Esta cor tornou-se o padrão não oficial para a divisão de tanques sabotadores, cuja principal tarefa é penetrar no território inimigo durante a noite. Dentro dos círculos militares, essas divisões de elite foram apelidadas de «Os pontos negros da morte».",
            isInventory: false,
            index: 2950,
            next_price: 100,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/black/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/black/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/black/texture"),
        },
        {
            id: "white",
            name: "Branca",
            description: "Esta tinta foi desenvolvida especificamente para operações terrestres em países com clima frio. Em áreas com neve, pode reduzir significativamente a probabilidade de detecção. Para aumentar as vendas, alguns fabricantes incluíram na embalagem um casaco quente e botas.",
            isInventory: false,
            index: 3000,
            next_price: 100,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/white/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/white/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/white/texture"),
        },
        {
            id: "orange",
            name: "Laranja",
            description: "Originalmente, não havia planos para incluir essa cor na lista oficial, pois não tinha nenhum valor prático, exceto talvez uma camuflagem decente em áreas desérticas. No entanto, psicólogos do exército provaram que esse tom específico de laranja tem um efeito terapêutico positivo. em tanques em estado de choque.",
            isInventory: false,
            index: 3050,
            next_price: 100,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/orange/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/orange/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/orange/texture"),
        },
        {
            id: "flora",
            name: "Flora",
            description: "Esta é uma das duas tintas projetadas especificamente para operações terrestres em um clima de latitude média. De acordo com relatórios da organização independente «True Camouflage», um tanque usando essa combinação específica de amarelo, verde e marrom tem menos probabilidade de ser detectado em tais regiões.",
            isInventory: false,
            index: 3100,
            next_price: 500,
            next_rank: 2,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/flora/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/flora/preview"),
            rank: 2,
            category: "paint",
            properts: [{"property":"SMOKY_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/flora/texture"),
        },
        {
            id: "marine",
            name: "Marinha",
            description: "Devido à sua alta resistência ao contato prolongado com água salgada, os navios-tanque inteligentes usam essa cor para pintar seus tanques por dentro, usando-o como um grande barril para salgar pepinos durante o inverno.",
            isInventory: false,
            index: 3150,
            next_price: 500,
            next_rank: 2,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/marine/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/marine/preview"),
            rank: 2,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/marine/texture"),
        },
        {
            id: "swamp",
            name: "Pântano",
            description: "Esta pintura foi criada depois que um líder de batalhão de tanques acidentalmente adormeceu e levou seus companheiros para um pântano, onde uma operação secreta para treinar sapos sabotadores estava sendo conduzida.",
            isInventory: false,
            index: 3200,
            next_price: 900,
            next_rank: 3,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/swamp/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/swamp/preview"),
            rank: 3,
            category: "paint",
            properts: [{"property":"TWINS_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 900,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/swamp/texture"),
        },
        {
            id: "forester",
            name: "Florestal",
            description: "Esta é uma das duas tintas projetadas especificamente para operações terrestres em um clima de latitude média. De acordo com relatórios da organização independente «True Camouflage», é menos provável que um tanque usando essa combinação específica de verde claro e escuro seja detectado em tal regiões.",
            isInventory: false,
            index: 3250,
            next_price: 1350,
            next_rank: 4,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/forester/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/forester/preview"),
            rank: 4,
            category: "paint",
            properts: [{"property":"RAILGUN_RESISTANCE","value":"12","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 1350,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/forester/texture"),
        },
        {
            id: "safari",
            name: "Safari",
            description: "Projetado por quem ama a emoção do safári, esta pintura mascara o tanque como uma zebra inócua, o que o torna perfeito para caçar predadores africanos, bem como petroleiros ingênuos.",
            isInventory: false,
            index: 3350,
            next_price: 1750,
            next_rank: 5,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/safari/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/safari/preview"),
            rank: 5,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"15","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 1750,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/safari/texture"),
        },
        {
            id: "invader",
            name: "Invasora",
            description: "Essa pintura foi desenvolvida em colaboração com uma comunidade de especialistas na era dos consoles de jogos de oito bits. Ela usa um exército de alienígenas de oito bits para mascarar o seu tanque e o marcará como um verdadeiro conhecedor de videogames.",
            isInventory: false,
            index: 3400,
            next_price: 1750,
            next_rank: 5,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/invader/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/invader/preview"),
            rank: 5,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"15","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 1750,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/invader/texture"),
        },
        {
            id: "metallic",
            name: "Metálica",
            description: "Existe o equívoco de que esta tinta se destina a substituir o envernizamento de superfícies. Na realidade, a natureza reflexiva desta tinta destina-se a interferir com dispositivos de rastreamento e radar.",
            isInventory: false,
            index: 3450,
            next_price: 2100,
            next_rank: 6,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/metallic/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/metallic/preview"),
            rank: 6,
            category: "paint",
            properts: [{"property":"THUNDER_RESISTANCE","value":"18","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 2100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/metallic/texture"),
        },
        {
            id: "lava",
            name: "Lava",
            description: "Uma cor experimental, testada pela primeira vez durante o conflito local na África Oriental. De acordo com psicólogos militares, esse padrão específico semelhante a um fogo divino desencadeará uma sensação de pânico nos inimigos.",
            isInventory: false,
            index: 3500,
            next_price: 2100,
            next_rank: 6,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/lava/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/lava/preview"),
            rank: 6,
            category: "paint",
            properts: [{"property":"FREEZE_RESISTANCE","value":"18","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 2100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/lava/texture"),
        },
        {
            id: "lead",
            name: "Chumbo",
            description: "O chumbo é conhecido há muito tempo por sua proteção contra a radiação. Essa tinta com infusão de chumbo aproveita essas propriedades.",
            isInventory: false,
            index: 3600,
            next_price: 3000,
            next_rank: 8,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/lead/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/lead/preview"),
            rank: 8,
            category: "paint",
            properts: [{"property":"SHAFT_RESISTANCE","value":"25","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 3000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/lead/texture"),
        },
        {
            id: "mary",
            name: "Mary",
            description: "Coberta com manchas vermelhas sangrentas, esta tinta foi feita para infligir horror ao inimigo. No entanto, os tanqueiros altamente experientes provavelmente perceberão que o que parece sangue é na verdade suco de tomate. Não é de admirar que a tinta seja chamada «Mary».",
            isInventory: false,
            index: 3650,
            next_price: 6500,
            next_rank: 9,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/mary/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/mary/preview"),
            rank: 9,
            category: "paint",
            properts: [{"property":"FREEZE_RESISTANCE","value":"15","subproperties":null},{"property":"TWINS_RESISTANCE","value":"8","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"8","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 6500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/mary/texture"),
        },
        {
            id: "carbon",
            name: "Carbono",
            description: "Uma combinação de fibra de carbono de alta tecnologia e tinta de alta resistência. Inclui uma substância especial destinada a interromper os sistemas de mira inimigos, embora isso seja proibido pela Diretoria de Inspeção de Movimento de Tanques.",
            isInventory: false,
            index: 3750,
            next_price: 6500,
            next_rank: 9,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/carbon/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/carbon/preview"),
            rank: 9,
            category: "paint",
            properts: [{"property":"TWINS_RESISTANCE","value":"6","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"18","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"6","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 6500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/carbon/texture"),
        },
        {
            id: "roger",
            name: "Caveira",
            description: "O temível motivo de caveira e ossos popularizado pelos piratas sedentos de sangue dos sete mares.",
            isInventory: false,
            index: 3800,
            next_price: 12500,
            next_rank: 10,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/roger/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/roger/preview"),
            rank: 10,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"8","subproperties":null},{"property":"TWINS_RESISTANCE","value":"16","subproperties":null},{"property":"SHOTGUN_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 12500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/roger/texture"),
        },
        {
            id: "fracture",
            name: "Fratura",
            description: "Uma camuflagem experimental desenvolvida para combate em climas tropicais.",
            isInventory: false,
            index: 3850,
            next_price: 12500,
            next_rank: 10,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/fracture/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/fracture/preview"),
            rank: 10,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"10","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"8","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"16","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 12500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/fracture/texture"),
        },
        {
            id: "vortex",
            name: "Redemoinho",
            description: "Lamentavelmente, os detalhes sobre a inspiração por trás dessa tinta são escassos. O designer simplesmente desapareceu um dia enquanto passeava tranquilamente à beira-mar. Os teóricos culpam os monstros marinhos.",
            isInventory: false,
            index: 3900,
            next_price: 12500,
            next_rank: 10,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/vortex/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/vortex/preview"),
            rank: 10,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"13","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"13","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"8","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 12500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/vortex/texture"),
        },
        {
            id: "chainmail",
            name: "Malha",
            description: "A cobertura única, estilizada e inspirada no correio em cadeia foi projetada para recriar as batalhas medievais em tanques. De acordo com a idéia do autor, as máquinas de aço com armadura de cavaleiro deveriam lutar por sua honra e pelo coração de uma bela garota tanque. Estamos absolutamente certos de que ninguém, ao criar esta tinta, jamais questionou se existiam tanques na Idade Média.",
            isInventory: false,
            index: 3950,
            next_price: 18500,
            next_rank: 11,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/chainmail/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/chainmail/preview"),
            rank: 11,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"22","subproperties":null},{"property":"ISIS_RESISTANCE","value":"11","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"5","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 18500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/chainmail/texture"),
        },
        {
            id: "corrosion",
            name: "Corrosão",
            description: "Para o petroleiro que quer ir além do uso de balas e se aventurar no reino da guerra química movida a tétano, a tinta «Corrosion» é a companhia perfeita.",
            isInventory: false,
            index: 4000,
            next_price: 18500,
            next_rank: 11,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/corrosion/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/corrosion/preview"),
            rank: 11,
            category: "paint",
            properts: [{"property":"RAILGUN_RESISTANCE","value":"10","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"15","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"15","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 18500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/corrosion/texture"),
        },
        {
            id: "tundra",
            name: "Tundra",
            description: "Dá ao seu tanque um visual intimidador e endurecido pela batalha. Ninguém ousará mexer com você.",
            isInventory: false,
            index: 4050,
            next_price: 18500,
            next_rank: 11,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/tundra/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/tundra/preview"),
            rank: 11,
            category: "paint",
            properts: [{"property":"SMOKY_RESISTANCE","value":"11","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"27","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 18500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/tundra/texture"),
        },
        {
            id: "alien",
            name: "Alienígena",
            description: "Há rumores de que esta camuflagem é uma réplica da cobertura de uma nave alienígena que foi derrubada no século passado pelas forças de «AVISO: Esta informação é confidencial — Mais investigações sobre o assunto serão recebidas com força mortal.»",
            isInventory: false,
            index: 4100,
            next_price: 24500,
            next_rank: 12,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/alien/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/alien/preview"),
            rank: 12,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"25","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"9","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"9","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 24500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/alien/texture"),
        },
        {
            id: "swash",
            name: "Marinho",
            description: "A fórmula da capa «Marinho» foi roubada de um laboratório secreto de codinome «Aqua», especializado em experimentos genéticos em peixes. Graças às suas propriedades especiais de reflexão de calor, esta tinta dá ao ar dentro do tanque um frescor refrescante à beira-mar.",
            isInventory: false,
            index: 4150,
            next_price: 24500,
            next_rank: 12,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/swash/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/swash/preview"),
            rank: 12,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"10","subproperties":null},{"property":"FIREBIRD_RESISTANCE","value":"18","subproperties":null},{"property":"TWINS_RESISTANCE","value":"11","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"5","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 24500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/swash/texture"),
        },
        {
            id: "pixel",
            name: "Pixel",
            description: "Camuflagem florestal feita com tecnologia experimental de pixels. Irrita ainda mais os entusiastas de alta resolução do que os pixels quebrados na tela.",
            isInventory: false,
            index: 4200,
            next_price: 30500,
            next_rank: 13,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/pixel/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/pixel/preview"),
            rank: 13,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"30","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"16","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 30500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/pixel/texture"),
        },
        {
            id: "guerrilla",
            name: "Guerrilha",
            description: "Essa tinta é montada a partir de uma variedade de materiais de sucata, fornecendo a cobertura perfeita para o petroleiro guerrilheiro que deseja tirar proveito do elemento surpresa.",
            isInventory: false,
            index: 4250,
            next_price: 30500,
            next_rank: 13,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/guerrilla/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/guerrilla/preview"),
            rank: 13,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"12","subproperties":null},{"property":"MACHINE_GUN_RESISTANCE","value":"26","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"8","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 30500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/guerrilla/texture"),
        },
        {
            id: "cedar",
            name: "Cedro",
            description: "Esta tinta é composta de flocos de pinha triturados. É ecologicamente correta e vem com dois sacos de pinhões descascados a cada segunda lata de tinta comprada.",
            isInventory: false,
            index: 4300,
            next_price: 30500,
            next_rank: 13,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/cedar/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/cedar/preview"),
            rank: 13,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"8","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"30","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"8","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 30500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/cedar/texture"),
        },
        {
            id: "in_love",
            name: "Apaixonado",
            description: "Projetado para os sofisticados e românticos, esta pintura irá satisfazer seu desejo por atributos militares esteticamente agradáveis. Também lhe renderá alguns segundos valiosos ao fascinar seu inimigo com a aparência extravagante de seu tanque, coberto de corações vermelhos.",
            isInventory: false,
            index: 4350,
            next_price: 30500,
            next_rank: 13,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/in_love/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/in_love/preview"),
            rank: 13,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"13","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"24","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 30500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/in_love/texture"),
        },
        {
            id: "desert",
            name: "Deserto",
            description: "Uma tinta especial ideal para operações no deserto. É criada pela pulverização de pó cristalino extraído dos dentes de um verme da areia. Para manter sua textura única, esta tinta não deve ser lavada.",
            isInventory: false,
            index: 4400,
            next_price: 36500,
            next_rank: 14,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/desert/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/desert/preview"),
            rank: 14,
            category: "paint",
            properts: [{"property":"TWINS_RESISTANCE","value":"8","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"26","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"8","subproperties":null},{"property":"SHOTGUN_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 36500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/desert/texture"),
        },
        {
            id: "dirty",
            name: "Lama",
            description: "Esta foi originalmente concebida como a terceira tinta projetada para operações terrestres em um clima de latitude média. No entanto, os militares decidiram mais tarde não incluí-la no pacote padrão, após repetidas tentativas de funcionários de limpeza para remover a textura de lama pintada da tampa.",
            isInventory: false,
            index: 4450,
            next_price: 42500,
            next_rank: 15,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/dirty/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/dirty/preview"),
            rank: 15,
            category: "paint",
            properts: [{"property":"RAILGUN_RESISTANCE","value":"24","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"32","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 42500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/dirty/texture"),
        },
        {
            id: "loam",
            name: "Argila",
            description: "Ninguém presta muita atenção em veículos sujos. A tinta «Argila» usa esse elemento psicológico para a vantagem do seu tanque, disfarçando-o como uma máquina suja. E quando seu inimigo vira as costas para você, é quando você ataca!",
            isInventory: false,
            index: 4600,
            next_price: 50500,
            next_rank: 16,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/loam/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/loam/preview"),
            rank: 16,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"30","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"11","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"11","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"11","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 50500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/loam/texture"),
        },
        {
            id: "sakura",
            name: "Sakura",
            description: "A pintura de desfile da divisão de tanques samurai. Ela traz harmonia interior e tranquilidade infinita. Nem mesmo as sirenes podem perturbar o estado de espírito do petroleiro cujo tanque está usando essa pintura.",
            isInventory: false,
            index: 4650,
            next_price: 50500,
            next_rank: 16,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/sakura/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/sakura/preview"),
            rank: 16,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"25","subproperties":null},{"property":"MACHINE_GUN_RESISTANCE","value":"12","subproperties":null},{"property":"ISIS_RESISTANCE","value":"25","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 50500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/sakura/texture"),
        },
        {
            id: "urban",
            name: "Urbana",
            description: "A melhor tinta para a batalha em ambientes urbanos. Funciona especialmente bem com arbustos de beira de estrada.",
            isInventory: false,
            index: 4700,
            next_price: 63500,
            next_rank: 17,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/urban/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/urban/preview"),
            rank: 17,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"15","subproperties":null},{"property":"FIREBIRD_RESISTANCE","value":"10","subproperties":null},{"property":"TWINS_RESISTANCE","value":"32","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 63500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/urban/texture"),
        },
        {
            id: "atom",
            name: "Átomo",
            description: "Um revestimento de proteção para tanques de cobertura em centros de pesquisa nuclear. O revestimento é tão de alta tecnologia que pode resistir a um impacto direto de uma carga nuclear, mas apenas ao custo de vaporizar instantaneamente o tanque sob o revestimento.",
            isInventory: false,
            index: 4750,
            next_price: 76600,
            next_rank: 18,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/atom/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/atom/preview"),
            rank: 18,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"33","subproperties":null},{"property":"FIREBIRD_RESISTANCE","value":"18","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"11","subproperties":null},{"property":"TWINS_RESISTANCE","value":"11","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 76600,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/atom/texture"),
        },
        {
            id: "digital",
            name: "Digital",
            description: "Além de ter propriedades de camuflagem excepcionais, esta tinta é extremamente durável e contém nanobots especiais para limpeza automática da pintura em combate.",
            isInventory: false,
            index: 4800,
            next_price: 76600,
            next_rank: 18,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/digital/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/digital/preview"),
            rank: 18,
            category: "paint",
            properts: [{"property":"SMOKY_RESISTANCE","value":"24","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"35","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"14","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 76600,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/digital/texture"),
        },
        {
            id: "hohloma",
            name: "Hohloma",
            description: "Uma criação cuja beleza lembra a habilidade dos artesãos russos, trabalhando em pequenas oficinas com paciência e dedicação.",
            isInventory: false,
            index: 4850,
            next_price: 76600,
            next_rank: 18,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/hohloma/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/hohloma/preview"),
            rank: 18,
            category: "paint",
            properts: [{"property":"FREEZE_RESISTANCE","value":"22","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"30","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"22","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 76600,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/hohloma/texture"),
        },
        {
            id: "electra",
            name: "Electra",
            description: "Uma pintura incrivelmente bonita que captura a elegância de um arco de eletricidade voando pelo ar.",
            isInventory: false,
            index: 4950,
            next_price: 90000,
            next_rank: 19,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/electra/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/electra/preview"),
            rank: 19,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"38","subproperties":null},{"property":"TWINS_RESISTANCE","value":"20","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"20","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 90000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/electra/texture"),
        },
        {
            id: "cherry",
            name: "Cereja",
            description: "Uma camuflagem altamente especializada para tanques florestais encarregados de proteger bosques de mogno raro contra caçadores ilegais.",
            isInventory: false,
            index: 5000,
            next_price: 103000,
            next_rank: 20,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/cherry/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/cherry/preview"),
            rank: 20,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"22","subproperties":null},{"property":"TWINS_RESISTANCE","value":"34","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"28","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 103000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/cherry/texture"),
        },
        {
            id: "blacksmith",
            name: "Ferreiro",
            description: "Um tributo aos mestres artesãos que moldam o aço em obras de arte mortais no calor abrasador da forja.",
            isInventory: false,
            index: 5050,
            next_price: 103000,
            next_rank: 20,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/blacksmith/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/blacksmith/preview"),
            rank: 20,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"40","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"18","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"26","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 103000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/blacksmith/texture"),
        },
        {
            id: "rustle",
            name: "Farfalha",
            description: "As folhas de outono podem farfalhar sob os rastros do seu tanque, mas seus oponentes ainda não poderão detectá-lo graças à mistura única de tons desta tinta.",
            isInventory: false,
            index: 5100,
            next_price: 103000,
            next_rank: 20,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/rustle/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/rustle/preview"),
            rank: 20,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"15","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"30","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"40","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 103000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/rustle/texture"),
        },
        {
            id: "python",
            name: "Píton",
            description: "Esta tinta é uma réplica exata da pele de uma píton gigante. Ela também replica as propriedades de extrema elasticidade da cobra, bem como sua textura escamosa.",
            isInventory: false,
            index: 5150,
            next_price: 103000,
            next_rank: 20,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/python/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/python/preview"),
            rank: 20,
            category: "paint",
            properts: [{"property":"FREEZE_RESISTANCE","value":"44","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"40","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 103000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/python/texture"),
        },
        {
            id: "sandstone",
            name: "Arenito",
            description: "A tinta combina as propriedades de mascaramento da areia, com a pedra temperada pelo vento. O conjunto «Sandstone» vem com calção de banho ou biquíni de escolha, óculos escuros e guarda-sol.",
            isInventory: false,
            index: 5200,
            next_price: 116000,
            next_rank: 21,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/sandstone/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/sandstone/preview"),
            rank: 21,
            category: "paint",
            properts: [{"property":"TWINS_RESISTANCE","value":"12","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"22","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"34","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"22","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 116000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/sandstone/texture"),
        },
        {
            id: "spark",
            name: "Faísca",
            description: "Luzes de fadas, luzes de palco, música das esferas - esta pintura pode ser descrita com muitas palavras, mas nenhuma delas pode descrevê-la completamente. A pintura «Spark» é escolhida por aqueles tanqueiros para quem o tanque não é apenas uma batalha máquina, mas também um meio de expressão.",
            isInventory: false,
            index: 5250,
            next_price: 116000,
            next_rank: 21,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/spark/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/spark/preview"),
            rank: 21,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"30","subproperties":null},{"property":"TWINS_RESISTANCE","value":"18","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"42","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 116000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/spark/texture"),
        },
        {
            id: "winter",
            name: "Inverno",
            description: "Esta tinta foi desenvolvida especialmente para batalhas em terrenos cobertos de neve. Originalmente, pretendia incluir uma pá de neve, mas o departamento financeiro não aprovou o custo extra.",
            isInventory: false,
            index: 5300,
            next_price: 129000,
            next_rank: 22,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/winter/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/winter/preview"),
            rank: 22,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"12","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"26","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"12","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"45","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 129000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/winter/texture"),
        },
        {
            id: "needle",
            name: "Agulha",
            description: "Usando abeto de áreas sustentáveis, a tinta «Needle» é preparada usando 25 metros quadrados de abeto, cortado e triturado em agulhas de madeira em miniatura e unidas usando um tipo especial de resina.",
            isInventory: false,
            index: 5350,
            next_price: 180000,
            next_rank: 24,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/needle/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/needle/preview"),
            rank: 24,
            category: "paint",
            properts: [{"property":"RICOCHET_RESISTANCE","value":"22","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"50","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"28","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 180000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/needle/texture"),
        },
        {
            id: "zeus",
            name: "Zeus",
            description: "Formada em homenagem ao deus grego conhecido por seu amor por raios, esta pintura sinalizará aos seus inimigos que você é uma força que não deve ser tomada de ânimo leve.",
            isInventory: false,
            index: 5400,
            next_price: 180000,
            next_rank: 24,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/zeus/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/zeus/preview"),
            rank: 24,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"50","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"25","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"25","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 180000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/zeus/texture"),
        },
        {
            id: "hive",
            name: "Colmeia",
            description: "Originalmente planejada como uma tinta com propriedades ofensivas ativas, a «Hive» deveria ser enriquecida com abelhas especiais antitanque. No entanto, esse plano foi abandonado devido aos inúmeros protestos de organizações que defendem os animais. Como resultado, a tinta agora só mantém sua cor e textura.",
            isInventory: false,
            index: 5450,
            next_price: 192000,
            next_rank: 25,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/hive/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/hive/preview"),
            rank: 25,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"42","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"26","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"32","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 192000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/hive/texture"),
        },
        {
            id: "rock",
            name: "Rocha",
            description: "As placas blindadas chamadas «The Rock» são extraídas de enormes formações rochosas, usando uma tecnologia egípcia antiga. Estacas secas são marteladas na rocha, depois encharcadas com água até incharem, quebrando a rocha em blocos lisos de pedra. Esta camuflagem é a definição de «feito à mão».",
            isInventory: false,
            index: 5500,
            next_price: 192000,
            next_rank: 25,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/rock/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/rock/preview"),
            rank: 25,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"28","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"12","subproperties":null},{"property":"TWINS_RESISTANCE","value":"50","subproperties":null},{"property":"SHOTGUN_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 192000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/rock/texture"),
        },
        {
            id: "mars",
            name: "Marte",
            description: "Diz-se que este revestimento estava sendo desenvolvido para uma divisão espacial para garantir a rápida liberação de Marte dos invasores alienígenas. A tinta foi colocada à venda somente para levantar fundos para transferir uma divisão de tanques para Marte.",
            isInventory: false,
            index: 5550,
            next_price: 204000,
            next_rank: 26,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/mars/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/mars/preview"),
            rank: 26,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"50","subproperties":null},{"property":"FIREBIRD_RESISTANCE","value":"30","subproperties":null},{"property":"ISIS_RESISTANCE","value":"20","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 204000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/mars/texture"),
        },
        {
            id: "prodigi",
            name: "Prodígio",
            description: "Uma pintura digital aprimorada com um padrão que se destina a distrair e desorientar seu inimigo, tornando-o mais propenso a errar ao atirar em você.",
            isInventory: false,
            index: 5600,
            next_price: 204000,
            next_rank: 26,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/prodigi/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/prodigi/preview"),
            rank: 26,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"7","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"23","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"50","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"20","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 204000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/prodigi/texture"),
        },
        {
            id: "graffiti",
            name: "Grafite",
            description: "Uma abordagem interessante para a camuflagem urbana. Fingindo ser uma vítima de hooligans de rua, seu tanque se funde perfeitamente com as áreas residenciais das selvas de concreto.",
            isInventory: false,
            index: 5650,
            next_price: 216000,
            next_rank: 27,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/graffiti/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/graffiti/preview"),
            rank: 27,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"50","subproperties":null},{"property":"TWINS_RESISTANCE","value":"25","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"25","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 216000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/graffiti/texture"),
        },
        {
            id: "mirage",
            name: "Miragem",
            description: "A camuflagem de última geração. Além de sua incrível capacidade de se misturar a praticamente qualquer plano de fundo, ela gera interferência de radar que torna muito mais difícil para o inimigo mirar a longa distância, e sua capacidade de calor extremamente alta permite que ela absorva parte da energia em caso de superaquecimento.",
            isInventory: false,
            index: 5653,
            next_price: 216000,
            next_rank: 27,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/mirage/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/mirage/preview"),
            rank: 27,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"35","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"22","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"20","subproperties":null},{"property":"MACHINE_GUN_RESISTANCE","value":"23","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 216000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/mirage/texture"),
        },
        {
            id: "irbis",
            name: "Irbis",
            description: "Um dos felinos mais misteriosos, o Irbis também é conhecido como o «leopardo-das-neves». Após uma série de expedições de alto risco e quinze acidentes, nossos pesquisadores conseguiram conter um leopardo-das-neves por tempo suficiente para copiar sua pelagem e criar o «Irbis» pintar.",
            isInventory: false,
            index: 5700,
            next_price: 216000,
            next_rank: 27,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/irbis/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/irbis/preview"),
            rank: 27,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"50","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"27","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"23","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 216000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/irbis/texture"),
        },
        {
            id: "emerald",
            name: "Esmeralda",
            description: "Os pesquisadores do laboratório de tintas «Style and Grill» trabalham há muito tempo em uma tinta que retenha o tom verde clássico de um tanque, ao mesmo tempo em que enfatiza o alto status de seu proprietário. O resultado é a tinta «Emerald», que parece ser iluminado por dentro.",
            isInventory: false,
            index: 5750,
            next_price: 228000,
            next_rank: 28,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/emerald/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/emerald/preview"),
            rank: 28,
            category: "paint",
            properts: [{"property":"TWINS_RESISTANCE","value":"35","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"50","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"15","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 228000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/emerald/texture"),
        },
        {
            id: "inferno",
            name: "Inferno",
            description: "A tinta «Inferno» é entregue por meios obscuros ao mercado negro das oficinas de sopro de vidro da China. Segundo os próprios produtores, sua aparência desafiadora simboliza força, coragem, sorte e longevidade. Uma tinta excelente para um atacante feroz.",
            isInventory: false,
            index: 5800,
            next_price: 228000,
            next_rank: 28,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/inferno/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/inferno/preview"),
            rank: 28,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"36","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"50","subproperties":null},{"property":"TWINS_RESISTANCE","value":"14","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 228000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/inferno/texture"),
        },
        {
            id: "nano",
            name: "Nano",
            description: "Uma camada espessa de nanoporonal é colocada no tanque a partir de uma lata pequena com uma escova ainda menor. O processo é longo, mas o resultado é agradável aos olhos. Do ponto de vista militar, esta é uma das mais dignas tentativas de adaptar a nanotecnologia aos tanques.",
            isInventory: false,
            index: 5850,
            next_price: 240000,
            next_rank: 29,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/nano/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/nano/preview"),
            rank: 29,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"35","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"32","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"22","subproperties":null},{"property":"FIREBIRD_RESISTANCE","value":"11","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 240000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/nano/texture"),
        },
        {
            id: "raccoon",
            name: "Guaxinim",
            description: "Essa pintura é um dos três itens obrigatórios para todos os membros do Worldwide Raccoon Club. O paletó e a gravata só são concedidos depois que o iniciado atinge o status de «Guaxinim Fofo». O negócio é sério.",
            isInventory: false,
            index: 5900,
            next_price: 240000,
            next_rank: 29,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/raccoon/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/raccoon/preview"),
            rank: 29,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"33","subproperties":null},{"property":"MACHINE_GUN_RESISTANCE","value":"27","subproperties":null},{"property":"ISIS_RESISTANCE","value":"19","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"21","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 240000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/raccoon/texture"),
        },
        {
            id: "clay",
            name: "Barro",
            description: "Esta tinta foi projetada para operações de sabotagem no pântano. Os tanques que usavam essa tinta estavam tão bem camuflados que nem as sanguessugas os notaram.",
            isInventory: false,
            index: 5950,
            next_price: 240000,
            next_rank: 29,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/clay/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/clay/preview"),
            rank: 29,
            category: "paint",
            properts: [{"property":"RICOCHET_RESISTANCE","value":"50","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"20","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"30","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 240000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/clay/texture"),
        },
        {
            id: "taiga",
            name: "Taiga",
            description: "A pintura de camuflagem «Taiga» mascara o tanque tão bem na vegetação densa, que você provavelmente poderia se aproximar de um alce com seu tanque...",
            isInventory: false,
            index: 6000,
            next_price: 240000,
            next_rank: 29,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/taiga/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/taiga/preview"),
            rank: 29,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"35","subproperties":null},{"property":"FIREBIRD_RESISTANCE","value":"24","subproperties":null},{"property":"TWINS_RESISTANCE","value":"17","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"24","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 240000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/taiga/texture"),
        },
        {
            id: "tiger",
            name: "Tigre",
            description: "Este revestimento não só parece uma pele de tigre, mas também torna seu tanque macio e fofo ao toque. Olhando para seu tanque neste revestimento, você pode treinar seu olho de tigre, o que lhe permitirá imobilizar os adversários assustados.",
            isInventory: false,
            index: 6050,
            next_price: 250000,
            next_rank: 30,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/tiger/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/tiger/preview"),
            rank: 30,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"47","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"35","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"18","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 250000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/tiger/texture"),
        },
        {
            id: "jade",
            name: "Jade",
            description: "Um spray de um raro jade marrom. Bonito, perfeito para camuflagem e ecologicamente correto.",
            isInventory: false,
            index: 6100,
            next_price: 250000,
            next_rank: 30,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/jade/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/jade/preview"),
            rank: 30,
            category: "paint",
            properts: [{"property":"THUNDER_RESISTANCE","value":"11","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"24","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"50","subproperties":null},{"property":"SHOTGUN_RESISTANCE","value":"15","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 250000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/jade/texture"),
        },
        {
            id: "picasso",
            name: "Picasso",
            description: "Picasso recebeu o nome de Pablo Picasso, o famoso artista cubista. Finos fragmentos poligonais da armadura formam um padrão abstrato verdadeiramente único,  que difunde até os golpes mais poderosos. Esta pintura é a escolha dos verdadeiros críticos de arte!",
            isInventory: false,
            index: 6150,
            next_price: 250000,
            next_rank: 30,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/picasso/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/picasso/preview"),
            rank: 30,
            category: "paint",
            properts: [{"property":"FREEZE_RESISTANCE","value":"20","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"20","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"27","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"33","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 250000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/picasso/texture"),
        },
        {
            id: "lumberjack",
            name: "Lenhador",
            description: "A camisa de um lenhador representa força e resistência às dificuldades do trabalho manual. Essa tinta se baseia nesse padrão para imbuir os mesmos valores no tanque que a veste.",
            isInventory: false,
            index: 6200,
            next_price: 250000,
            next_rank: 30,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/lumberjack/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/lumberjack/preview"),
            rank: 30,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"10","subproperties":null},{"property":"ISIS_RESISTANCE","value":"30","subproperties":null},{"property":"FIREBIRD_RESISTANCE","value":"30","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"30","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 250000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/lumberjack/texture"),
        },
        {
            id: "africa",
            name: "Africa",
            description: "Essa tinta apresenta padrões tradicionais africanos usados pelos xamãs africanos, que acreditam que ela pode proteger os tanques contra danos.",
            isInventory: false,
            index: 6250,
            next_price: 250000,
            next_rank: 30,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/africa/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/africa/preview"),
            rank: 30,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"20","subproperties":null},{"property":"MACHINE_GUN_RESISTANCE","value":"30","subproperties":null},{"property":"TWINS_RESISTANCE","value":"25","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"25","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 250000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/africa/texture"),
        },
        {
            id: "acid",
            name: "Acid",
            description: "A corrosive, acid-toned coat that seems to dissolve everything around it.",
            isInventory: false,
            index: 6300,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/acid/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/acid/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/acid/texture"),
        },
        {
            id: "champion",
            name: "Champion",
            description: "Reserved for the true champions of the battlefield.",
            isInventory: false,
            index: 6350,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/champion/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/champion/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/champion/texture"),
        },
        {
            id: "impulse",
            name: "Impulse",
            description: "Energetic lines that convey pure speed and momentum.",
            isInventory: false,
            index: 6400,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/impulse/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/impulse/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/impulse/texture"),
        },
        {
            id: "frost",
            name: "Frost",
            description: "A frozen finish covered in crystals of ice.",
            isInventory: false,
            index: 6450,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/frost/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/frost/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/frost/texture"),
        },
        {
            id: "star",
            name: "Star",
            description: "Shines like a star amid the darkness of combat.",
            isInventory: false,
            index: 6500,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/star/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/star/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/star/texture"),
        },
        {
            id: "bronze",
            name: "Bronze",
            description: "A metallic bronze finish weathered by battle.",
            isInventory: false,
            index: 6550,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/bronze/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/bronze/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/bronze/texture"),
        },
        {
            id: "silver",
            name: "Silver",
            description: "An elegant, imposing silver shine.",
            isInventory: false,
            index: 6600,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/silver/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/silver/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/silver/texture"),
        },
        {
            id: "veteran",
            name: "Veteran",
            description: "The mark of one who has survived countless battles.",
            isInventory: false,
            index: 6650,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/veteran/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/veteran/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/veteran/texture"),
        },
        {
            id: "gladiator",
            name: "Gladiator",
            description: "Forged in the arena for the most relentless warriors.",
            isInventory: false,
            index: 6700,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/gladiator/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/gladiator/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/gladiator/texture"),
        },
        {
            id: "helper",
            name: "Helper",
            description: "Granted to those who help the community grow.",
            isInventory: false,
            index: 6800,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/helper/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/helper/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/helper/texture"),
        },
        {
            id: "visual_disruptor",
            name: "Visual Disruptor",
            description: "An animated pattern that distorts the perception of anyone who faces it.",
            isInventory: false,
            index: 6850,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/visual_disruptor/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/visual_disruptor/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/visual_disruptor/texture"),
        },
        {
            id: "tesseract_camo",
            name: "Tesseract Camo",
            description: "A shifting four-dimensional camouflage that never stays the same.",
            isInventory: false,
            index: 6900,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/tesseract_camo/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/tesseract_camo/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/tesseract_camo/texture"),
        },
        {
            id: "symbiote",
            name: "Symbiote",
            description: "A living coat that writhes and pulses across the armor.",
            isInventory: false,
            index: 6950,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/symbiote/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/symbiote/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/symbiote/texture"),
        },
        {
            id: "spinner",
            name: "Spinner",
            description: "A hypnotic spinning pattern that keeps the eye off balance.",
            isInventory: false,
            index: 7000,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/spinner/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/spinner/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/spinner/texture"),
        },
        {
            id: "galaxy",
            name: "Galaxy",
            description: "A swirling animated galaxy that drifts across the armor.",
            isInventory: false,
            index: 7050,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/galaxy/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/galaxy/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/galaxy/texture"),
        },
    ],
    // Supplies (consumables). category "inventory", type 4. previewResourceId/baseItemId are the
    // client's built-in inventory icon ids (small fixed numbers), not CDN resource idLows. The 5
    // consumables are owned in quantity (shown in the depot with a `count`); "1000_scores" is
    // consumed instantly on purchase and grants experience (rank points) instead of stacking.
    supplies: [
        { id: "health", name: "Kit de Reparação", description: "Restaura gradualmente a «saúde» do tanque até a cura completa.", index: 7600, type: 4, rank: 3, price: 150 },
        { id: "armor", name: "Blindagem Dupla", description: "Dobra a resistência do tanque por um curto período.", index: 7650, type: 4, rank: 4, price: 50 },
        { id: "double_damage", name: "Destruição Dupla", description: "Dobra o dano causado pelo tanque por um curto período.", index: 7700, type: 4, rank: 4, price: 50 },
        { id: "n2o", name: "Aumento de Velocidade", description: "Aumenta a velocidade e a aceleração do tanque por um curto período.", index: 7750, type: 4, rank: 4, price: 50 },
        { id: "mine", name: "Mina", description: "Coloca uma mina invisível que explode quando um inimigo se aproxima.", index: 7800, type: 4, rank: 5, price: 50 },
        { id: "1000_scores", name: "1000 experiência", description: "Concede 1000 pontos de experiência. É usado automaticamente logo após a compra.", index: 7550, type: 4, rank: 11, price: 2000, instantScore: 1000 },
    ],
};