import { ResourceManager } from "@/utils/resource.manager";
import { ResourceId } from "@/generated/resourceTypes";
import { hullsData, toHullBlueprint } from "@/config/hulls.data";
import { turretsData, toTurretBlueprint } from "@/config/turrets.data";

// Resource keys (in resourceTypes.ts) for the supply preview icons. The actual images were
// downloaded from the official CDN into resources/bonuses/<X>/preview, so they're served by OUR
// resource server with our own idLows — works for any client.
export const supplyPreviewResources: Record<string, ResourceId> = {
    health: "bonuses/health/preview",
    armor: "bonuses/armor/preview",
    double_damage: "bonuses/damage/preview",
    n2o: "bonuses/nitro/preview",
    mine: "bonuses/mine/preview",
    "1000_scores": "bonuses/scores/preview",
};

export const itemBlueprints = {
    turrets: turretsData.map(toTurretBlueprint),
    hulls: hullsData.map(toHullBlueprint),
    paints: [
        {
            id: "green",
            name: "Verde",
            description: "Um tributo à tradição do tanque clássico, esta cor simples, tão amada por designers de todo o mundo, tornou-se uma tinta padrão para modelos de fábrica.",
            isInventory: false,
            index: 1100,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/green/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/green/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/green/texture"),
        },
        {
            id: "holiday",
            name: "Feriado",
            description: "Uma tinta única e «inteligente» que pode mudar sua aparência dependendo da ocasião. Em um dia normal, é simplesmente uma textura quadriculada em preto e branco. Mas quando chega um feriado, sua aparência muda drasticamente.",
            isInventory: false,
            index: 1200,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/holiday/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/holiday/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/holiday/texture"),
        },
        {
            id: "red",
            name: "Vermelha",
            description: "A cor vermelha - a personificação da raiva e da coragem. Também tem a aplicação prática de poder esconder qualquer vestígio de sangue inimigo.",
            isInventory: false,
            index: 2850,
            next_price: 100,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/red/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/red/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/red/texture"),
        },
        {
            id: "blue",
            name: "Azul",
            description: "Esta pintura foi adicionada à lista oficial em memória de um projeto fracassado - o desenvolvimento de um tanque anfíbio codinome «Catfish». Os designers estavam planejando dar ao <Catfish> a capacidade de se mover sob as águas de rios rasos, permitindo que ele tomar posição atrás das linhas inimigas. A cor azul seria perfeita para camuflagem.",
            isInventory: false,
            index: 2900,
            next_price: 100,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/blue/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/blue/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/blue/texture"),
        },
        {
            id: "black",
            name: "Preta",
            description: "Esta cor tornou-se o padrão não oficial para a divisão de tanques sabotadores, cuja principal tarefa é penetrar no território inimigo durante a noite. Dentro dos círculos militares, essas divisões de elite foram apelidadas de «Os pontos negros da morte».",
            isInventory: false,
            index: 2950,
            next_price: 100,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/black/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/black/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/black/texture"),
        },
        {
            id: "white",
            name: "Branca",
            description: "Esta tinta foi desenvolvida especificamente para operações terrestres em países com clima frio. Em áreas com neve, pode reduzir significativamente a probabilidade de detecção. Para aumentar as vendas, alguns fabricantes incluíram na embalagem um casaco quente e botas.",
            isInventory: false,
            index: 3000,
            next_price: 100,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/white/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/white/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/white/texture"),
        },
        {
            id: "orange",
            name: "Laranja",
            description: "Originalmente, não havia planos para incluir essa cor na lista oficial, pois não tinha nenhum valor prático, exceto talvez uma camuflagem decente em áreas desérticas. No entanto, psicólogos do exército provaram que esse tom específico de laranja tem um efeito terapêutico positivo. em tanques em estado de choque.",
            isInventory: false,
            index: 3050,
            next_price: 100,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/orange/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/orange/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/orange/texture"),
        },
    ],
    // Supplies (consumables). category "inventory", type 4. previewResourceId/baseItemId are the
    // client's built-in inventory icon ids (small fixed numbers), not CDN resource idLows. The 5
    // consumables are owned in quantity (shown in the depot with a `count`); "1000_scores" is
    // consumed instantly on purchase and grants experience (rank points) instead of stacking.
    supplies: [
        { id: "health", name: "Kit de Reparação", description: "Restaura gradualmente a «saúde» do tanque até a cura completa.", index: 7600, type: 4, rank: 3, price: 150 },
        { id: "armor", name: "Blindagem Dupla", description: "Dobra a resistência do tanque por um curto período.", index: 7650, type: 4, rank: 4, price: 50 },
        { id: "double_damage", name: "Destruição Dupla", description: "Dobra o dano causado pelo tanque por um curto período.", index: 7700, type: 4, rank: 4, price: 50 },
        { id: "n2o", name: "Aumento de Velocidade", description: "Aumenta a velocidade e a aceleração do tanque por um curto período.", index: 7750, type: 4, rank: 4, price: 50 },
        { id: "mine", name: "Mina", description: "Coloca uma mina invisível que explode quando um inimigo se aproxima.", index: 7800, type: 4, rank: 5, price: 50 },
        { id: "1000_scores", name: "1000 experiência", description: "Concede 1000 pontos de experiência. É usado automaticamente logo após a compra.", index: 7550, type: 4, rank: 11, price: 2000, instantScore: 1000 },
    ],
};