import { CALLBACK } from "@/config/constants";
import { HideLoader, LoadDependencies } from "@/features/loader/loader.packets";
import { SocialNetwork } from "@/features/social/social.packets";
import { CaptchaLocation, InviteEnabled, Ping } from "@/features/system/system.packets";
import { GameClient } from "@/server/game.client";
import { GameServer } from "@/server/game.server";
import { ResourceId } from "@/generated/resourceTypes";
import generateCaptcha from "@/utils/captcha.generator";
import { ResourceManager } from "@/utils/resource.manager";
import * as AuthPackets from "./auth.packets";

export class AuthWorkflow {
    public static async sendLoginScreenData(client: GameClient, server: GameServer): Promise<void> {
        client.sendPacket(new Ping());
        client.sendPacket(new SocialNetwork(server.getSocialNetworks()));
        client.sendPacket(new CaptchaLocation(server.configService.getCaptchaLocations()));

        const tipResourceIds: ResourceId[] = ["tips/tip_1", "tips/tip_2", "tips/tip_3"];

        const dependencies = {
            resources: ResourceManager.getBulkResources(tipResourceIds),
        };
        client.sendPacket(new LoadDependencies(dependencies, CALLBACK.TIPS_LOADED));
    }

    public static async sendMainLoginResources(client: GameClient, server: GameServer): Promise<void> {
        const resourceIds: ResourceId[] = [
            "ui/language_images",
            "ui/login_background",
            "ui/quests/icons/battle_score",
            "ui/quests/icons/get_crystal",
            "ui/quests/icons/kill_enemies",
            "ui/quests/icons/gold_box",
            "ui/quests/window/week1/quest_chain",
            "ui/quests/window/week2/quest_chain",
            "ui/quests/window/week3/quest_chain",
            "ui/quests/window/week4/quest_chain",
            "ui/quests/window/week1/final_reward",
            "ui/quests/window/week2/final_reward",
            "ui/quests/window/week3/final_reward",
            "ui/quests/window/week4/final_reward",
            "sounds/notifications/battle_invite",
            "sounds/notifications/gold_box_siren",
            "map/zone/summer/preview",
            "map/zone/winter/preview",
            "map/zone/space/preview",
            "map/zone/space/preview",
            "map/kolhoz/summer/preview",
            "map/kolhoz/winter/preview",
            "map/kolhoz/space/preview",
            "map/kolhoz/space/preview",
            "map/atra/summer/preview",
            "map/atra/winter/preview",
            "map/atra/space/preview",
            "map/atra/space/preview",
            "map/gravity/summer/preview",
            "map/gravity/winter/preview",
            "map/gravity/space/preview",
            "map/gravity/space/preview",
            "map/sandbox/summer/preview",
            "map/sandbox/winter/preview",
            "map/sandbox/summer_night/preview",
            "map/sandbox/space/preview",
            "map/sandbox/space/preview",
            "map/garder/summer/preview",
            "map/garder/winter/preview",
            "map/garder/space/preview",
            "map/garder/space/preview",
            "map/skyscrapers/summer/preview",
            "map/skyscrapers/space/preview",
            "map/industrial_zone/summer/preview",
            "map/industrial_zone/winter/preview",
            "map/industrial_zone/space/preview",
            "map/industrial_zone/space/preview",
            "map/combe/summer/preview",
            "map/combe/winter/preview",
            "map/combe/space/preview",
            "map/combe/space/preview",
            "map/novel/summer/preview",
            "map/novel/winter/preview",
            "map/novel/space/preview",
            "map/novel/space/preview",
            "map/deathtrack/summer/preview",
            "map/deathtrack/winter/preview",
            "map/deathtrack/space/preview",
            "map/deathtrack/space/preview",
            "map/montecarlo/summer/preview",
            "map/montecarlo/winter/preview",
            "map/montecarlo/space/preview",
            "map/montecarlo/space/preview",
            "map/sandal/summer/preview",
            "map/sandal/winter/preview",
            "map/sandal/space/preview",
            "map/sandal/space/preview",
            "map/camp/summer/preview",
            "map/camp/winter/preview",
            "map/camp/space/preview",
            "map/camp/space/preview",
            "map/fortknox/summer/preview",
            "map/fortknox/winter/preview",
            "map/fortknox/space/preview",
            "map/fortknox/space/preview",
            "map/trains/summer/preview",
            "map/trains/winter/preview",
            "map/trains/space/preview",
            "map/trains/space/preview",
            "map/canyon/summer/preview",
            "map/canyon/winter/preview",
            "map/canyon/space/preview",
            "map/canyon/space/preview",
            "map/solikamsk/summer/preview",
            "map/solikamsk/winter/preview",
            "map/solikamsk/space/preview",
            "map/solikamsk/space/preview",
            "map/legacy/summer/preview",
            "map/wave/summer/preview",
            "map/wave/winter/preview",
            "map/wave/space/preview",
            "map/wave/space/preview",
            "map/rio/summer/preview",
            "map/rio/summer_night/preview",
            "map/rio/space/preview",
            "map/rio/space/preview",
            "map/polygon/summer/preview",
            "map/polygon/winter/preview",
            "map/polygon/summer_night/preview",
            "map/polygon/space/preview",
            "map/polygon/space/preview",
            "map/esplanade/summer/preview",
            "map/esplanade/winter/preview",
            "map/esplanade/space/preview",
            "map/esplanade/space/preview",
            "map/ny_trassa/winter_night/preview",
            "map/minecraft/summer/preview",
            "map/duel/summer/preview",
            "map/duel/winter/preview",
            "map/duel/space/preview",
            "map/duel/space/preview",
            "map/cross/summer/preview",
            "map/cross/winter/preview",
            "map/cross/space/preview",
            "map/cross/space/preview",
            "map/dusseldorf/summer/preview",
            "map/dusseldorf/winter/preview",
            "map/dusseldorf/space/preview",
            "map/dusseldorf/space/preview",
            "map/dualiti/summer/preview",
            "map/dualiti/winter/preview",
            "map/dualiti/space/preview",
            "map/dualiti/space/preview",
            "map/new_year_yorkshir/winter/preview",
            "map/gallery/summer/preview",
            "map/highway/summer/preview",
            "map/highway/winter/preview",
            "map/highway/space/preview",
            "map/highway/space/preview",
            "map/bridges/summer/preview",
            "map/bridges/winter/preview",
            "map/bridges/space/preview",
            "map/bridges/space/preview",
            "map/magistral/summer/preview",
            "map/magistral/winter/preview",
            "map/magistral/space/preview",
            "map/magistral/space/preview",
            "map/brest/summer/preview",
            "map/brest/winter/preview",
            "map/brest/space/preview",
            "map/brest/space/preview",
            "map/highland/summer/preview",
            "map/highland/winter/preview",
            "map/highland/space/preview",
            "map/highland/space/preview",
            "map/platform/space/preview",
            "map/platform/space/preview",
            "map/platform/space/preview",
            "map/gubakha/summer/preview",
            "map/gubakha/winter/preview",
            "map/gubakha/space/preview",
            "map/gubakha/space/preview",
            "map/osa/summer/preview",
            "map/osa/winter/preview",
            "map/osa/space/preview",
            "map/osa/space/preview",
            "map/scope/summer/preview",
            "map/scope/winter/preview",
            "map/scope/space/preview",
            "map/scope/space/preview",
            "map/island/summer/preview",
            "map/island/winter/preview",
            "map/island/space/preview",
            "map/island/space/preview",
            "map/stadium/summer/preview",
            "map/stadium/winter/preview",
            "map/stadium/summer_night/preview",
            "map/stadium/space/preview",
            "map/stadium/space/preview",
            "map/ny_island/winter_night/preview",
            "map/boombox/summer/preview",
            "map/boombox/winter/preview",
            "map/boombox/space/preview",
            "map/boombox/space/preview",
            "map/magadan/summer/preview",
            "map/magadan/winter/preview",
            "map/magadan/space/preview",
            "map/magadan/space/preview",
            "map/cosmicstation/space/preview",
            "map/siege/summer/preview",
            "map/siege/winter/preview",
            "map/siege/space/preview",
            "map/siege/space/preview",
            "map/shortbridge/summer/preview",
            "map/shortbridge/winter/preview",
            "map/shortbridge/space/preview",
            "map/shortbridge/space/preview",
            "map/farm/summer/preview",
            "map/farm/winter/preview",
            "map/farm/space/preview",
            "map/farm/space/preview",
            "map/chornobyl/summer/preview",
            "map/chornobyl/winter/preview",
            "map/chornobyl/space/preview",
            "map/chornobyl/space/preview",
            "map/kungur/summer/preview",
            "map/kungur/winter/preview",
            "map/kungur/space/preview",
            "map/kungur/space/preview",
            "map/valley/summer/preview",
            "map/valley/winter/preview",
            "map/valley/space/preview",
            "map/valley/space/preview",
            "map/skirmish/summer/preview",
            "map/skirmish/summer_night/preview",
            "map/skirmish/space/preview",
            "map/skirmish/space/preview",
            "map/ny_aleksandrovsk/winter_night/preview",
            "map/2042/summer/preview",
            "map/2042/winter/preview",
            "map/2042/space/preview",
            "map/2042/space/preview",
            "map/arena/summer/preview",
            "map/arena/winter/preview",
            "map/arena/space/preview",
            "map/arena/space/preview",
            "map/pingpong/summer/preview",
            "map/pingpong/winter/preview",
            "map/pingpong/space/preview",
            "map/pingpong/space/preview",
            "map/losttemple/summer/preview",
            "map/losttemple/winter/preview",
            "map/losttemple/space/preview",
            "map/losttemple/space/preview",
            "map/factory/summer/preview",
            "map/factory/space/preview",
            "map/factory/space/preview",
            "map/iran/summer/preview",
            "map/iran/winter/preview",
            "map/iran/summer_night/preview",
            "map/iran/winter_night/preview",
            "map/iran/space/preview",
            "map/iran/space/preview",
            "map/courage/summer/preview",
            "map/courage/winter/preview",
            "map/courage/space/preview",
            "map/courage/space/preview",
            "map/pass/summer/preview",
            "map/pass/winter/preview",
            "map/pass/space/preview",
            "map/pass/space/preview",
            "map/skylark/summer/preview",
            "map/skylark/winter/preview",
            "map/skylark/space/preview",
            "map/skylark/space/preview",
            "map/berlin/summer/preview",
            "map/berlin/winter/preview",
            "map/berlin/space/preview",
            "map/berlin/space/preview",
            "map/desert/summer/preview",
            "map/desert/winter/preview",
            "map/desert/space/preview",
            "map/desert/space/preview",
            "map/tribute/summer/preview",
            "map/tribute/winter/preview",
            "map/tribute/space/preview",
            "map/tribute/space/preview",
            "map/opposition/summer/preview",
            "map/opposition/winter/preview",
            "map/opposition/space/preview",
            "map/opposition/space/preview",
            "map/wolfenstein/summer/preview",
            "map/wolfenstein/winter/preview",
            "map/wolfenstein/space/preview",
            "map/wolfenstein/space/preview",
            "map/madness_space/space/preview",
            "map/silence/summer/preview",
            "map/silence/winter/preview",
            "map/silence/summer_night/preview",
            "map/silence/space/preview",
            "map/silence/space/preview",
            "map/madness_old/space/preview",
            "map/future/summer/preview",
            "map/future/summer_night/preview",
            "map/future/space/preview",
            "map/future/space/preview",
            "map/aleksandrovsk/summer/preview",
            "map/aleksandrovsk/winter/preview",
            "map/aleksandrovsk/summer_night/preview",
            "map/aleksandrovsk/space/preview",
            "map/aleksandrovsk/space/preview",
            "map/bobruisk/summer/preview",
            "map/bobruisk/winter/preview",
            "map/bobruisk/space/preview",
            "map/bobruisk/space/preview",
            "map/massacre/summer/preview",
            "map/massacre/winter/preview",
            "map/massacre/space/preview",
            "map/massacre/space/preview",
            "map/hill/summer/preview",
            "map/hill/winter/preview",
            "map/hill/space/preview",
            "map/hill/space/preview",
            "map/rift/summer/preview",
            "map/rift/winter/preview",
            "map/rift/space/preview",
            "map/rift/space/preview",
            "map/edinburgh/summer/preview",
            "map/edinburgh/winter/preview",
            "map/edinburgh/space/preview",
            "map/edinburgh/space/preview",
            "map/abyss/summer/preview",
            "map/abyss/winter/preview",
            "map/abyss/space/preview",
            "map/abyss/space/preview",
            "map/forest/summer/preview",
            "map/forest/winter/preview",
            "map/forest/space/preview",
            "map/forest/space/preview",
            "map/silence_moon/space/preview",
            "map/deck9/summer/preview",
            "map/deck9/winter/preview",
            "map/deck9/space/preview",
            "map/deck9/space/preview",
            "map/parma/summer/preview",
            "map/parma/winter/preview",
            "map/parma/space/preview",
            "map/parma/space/preview",
            "map/subway/summer/preview",
            "map/subway/winter/preview",
            "map/subway/space/preview",
            "map/subway/space/preview",
            "map/station/summer/preview",
            "map/station/winter/preview",
            "map/station/space/preview",
            "map/station/space/preview",
            "map/barda/summer/preview",
            "map/barda/winter/preview",
            "map/barda/summer_night/preview",
            "map/barda/space/preview",
            "map/barda/space/preview",
            "map/redalert/summer/preview",
            "map/redalert/winter/preview",
            "map/redalert/space/preview",
            "map/redalert/space/preview",
            "map/crash/summer/preview",
            "map/molotov/summer/preview",
            "map/molotov/winter/preview",
            "map/molotov/space/preview",
            "map/molotov/space/preview",
            "map/serpuhov/summer/preview",
            "map/serpuhov/winter/preview",
            "map/serpuhov/space/preview",
            "map/serpuhov/space/preview",
            "map/noise/summer/preview",
            "map/noise/winter/preview",
            "map/noise/space/preview",
            "map/noise/space/preview",
            "bonuses/nitro/model",
            "bonuses/damage/model",
            "bonuses/armor/model",
            "bonuses/health/model",
            "bonuses/crystal",
            "bonuses/gold",
            "bonuses/special",
            "bonuses/moon",
            "bonuses/pumpkin",
            "bonuses/parachute/cord",
            "bonuses/parachute/inner",
            "bonuses/parachute/main",
            "sounds/bonus_pickup",
            "sounds/battle/tank_explosion",
        ];

        // Clan rankings podium image, referenced by the post-login InitUserClanModelsPacket. Register
        // it pre-login so the client knows it before that packet (else the packet parse throws
        // "Resource not found" and the clan module/button is skipped).
        resourceIds.push("clan/podium");

        const dependencies = {
            resources: ResourceManager.getBulkResources(resourceIds),
        };
        client.sendPacket(new LoadDependencies(dependencies, CALLBACK.LOGIN_FORM));
    }

    public static initializeLoginForm(client: GameClient, server: GameServer): void {
        client.sendPacket(new InviteEnabled({ requireInviteCode: server.getNeedInviteCode() }));

        const loginForm = server.getLoginForm();
        client.sendPacket(new AuthPackets.Registration({ bgResource: loginForm.bgResource, enableRequiredEmail: loginForm.enableRequiredEmail, maxPasswordLength: loginForm.maxPasswordLength, minPasswordLength: loginForm.minPasswordLength }));

        client.sendPacket(new HideLoader());
    }

    public static handleInvalidRecoveryCode(client: GameClient): void {
        const captcha = generateCaptcha();
        client.captchaSolution = captcha.text;

        client.sendPacket(new AuthPackets.RecoveryEmailInvalidCode());
        client.sendPacket(new AuthPackets.Captcha({ view: 3, image: captcha.image }));
    }
}